spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/root
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true
    
auth:
  header: Authorization
  
server:
  port: 8080
jwt:
  secret: jwtsecretkey